import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navigation from '@/components/Navigation'
import Hero from '@/components/Hero'
import { Rubik_Distressed } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

const rubik = Rubik_Distressed({
  subsets: ['latin'],
  weight: ['400']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${rubik.className} bg-black`}>
        <Navigation />
        <Hero />
        {children}
        
        </body>
    </html>
  )
}
